### ISSUE TITLE
Make use of the :label and :value modifier

### ISSUE THREAD

**Issue by arnemulder** [csalzano/gravityforms-html-fields-merge-tags#1]
Nice plugin, I've used it, works well. It returns the value of the GF field, but it would be nice to also use the label.
{mergetag:1:value} and {mergetag:1:label}

**Comment by csalzano** [comment]
Thanks for the feedback! I might not circle back to this project for a few months, but I agree with your suggestion.

**Comment by csalzano** [comment]
I just pushed version 1.0.0 that includes support for modifiers like value and label in Field Merge Tags.
