### ISSUE TITLE
This isn't an issue, just a shoutout lol

### ISSUE THREAD

**Issue by newventuredigital** [csalzano/gravityforms-html-fields-merge-tags#5]
I just tried the plugin on a 6-page, 20+ inputs, calculations, conditional logic form. It worked beautifully! I'm developing this complex form for my Mother's Quilting Business, awesome sauce!

**Comment by csalzano** [comment]
Glad to help. I built this add-on for confirmation pages--to show users what they entered right before submitting.

I maintain another extension for Gravity Forms if you're in deep https://wordpress.org/plugins/power-boost-for-gravity-forms/

**Comment by newventuredigital** [comment]
That is exactly what I used it for. A quick recap of details from the previous pages. Are you on Facebook? Wanted to message you but I deleted my twitter years and years ago lol

**Comment by csalzano** [comment]
I just launched a new version of Power Boost that contains this plugin as a feature. 🍻
